language: rust
sudo: required
dist: trusty

rust:
  - stable
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: osx
      osx_image: xcode8.3
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

before_install:
  - eval "${MATRIX_EVAL}"
  - export CC CXX

script:
  - cargo build --verbose --all
  - cargo test --verbose --all

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo