language: rust
sudo: required
dist: trusty

rust:
  - stable

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
            - g++-5
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"
    - os: osx
      osx_image: xcode8.3
      env:
        - MATRIX_EVAL="brew update && rm '/usr/local/include/c++' && brew install gcc@5 && CC=gcc-5 && CXX=g++-5"
    - os: osx
      osx_image: xcode8.3
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

before_install:
  - set -e
  - eval "${MATRIX_EVAL}"

script:
  - cargo build --verbose --all
  - cargo test --verbose --all

after_script:
  - set +e

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo